module.exports = {
  DEMO_MODE: true,
  TRADING_ENABLED: true,
  ASSET: 'btc',
  STARTING_BANKROLL: 4000,

  BASE_WINDOW_MINUTES: 15,
  HEDGE_SHARES: 50,
  BASE_UP_SHARES: 150,

  POLL_INTERVAL_MS: 2000,
  STATE_FILE: __dirname + '/state.json',
  TAKER_SLIPPAGE_MIN: 0.001,
  TAKER_SLIPPAGE_MAX: 0.005,
  BASE_TAKER_FEE_RATE: 0.07,
  RESOLUTION_WIN_THRESHOLD: 0.90,
};
